CREATE TABLE inventory (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	isbn VARCHAR(13) NOT NULL,
	title VARCHAR(150) NOT NULL,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	copies INTEGER NOT NULL
);

CREATE TABLE history (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	title VARCHAR(150) NOT NULL,
	isbn VARCHAR(13) NOT NULL,
	action VARCHAR(50) NOT NULL,
	modification_time TIMESTAMPTZ NOT NULL
);
